### ISSUE TITLE
why vue-infinite-loading not work in mobile ?

### ISSUE THREAD

**Issue by HAMZABoxer98** [PeachScript/vue-infinite-loading#121]
### Version

2.2
### Vue.js version

2.5.2
### What is expected?

works on mobile browsers !
### What is actually happening?

simply not working :'(
### How to reproduce this problem?
first i call the getPosts from mounted then with v-if i show (create) the div wich contain the posts with the infinite-loading

**Comment by PeachScript** [comment]
You're the first one to report that this component cannot working in the mobile browsers, so I think your conclusion is too early. In order to find the real reason, you need to provide a live demo to reproduce your problem, and provide the device informations(include serial, OS, browser version and etc.).
