### ISSUE TITLE
infinite-loading doesnt work when used with flexbox

### ISSUE THREAD

**Issue by Isa79** [PeachScript/vue-infinite-loading#122]
### Version
2.2.3

### Vue.js version
2.5.5

### What is expected?
When using vue-infinite-loading with flexbox it doesnt work. I don't know why that is.

### How to reproduce this problem?
HTML
```
   <div class="wrapper">
     <item v-for="(item, i) in items" :key="i" ></item>
     <infinite-loading @infinite="infiniteHandler" :distance="500">
       <span slot="no-more"> </span>
       <span slot="spinner"> </span>
     </infinite-loading>
   </div>
```
CSS
```
  .wrapper {
    display: flex;
    flex-flow: row wrap;
    justify-content: center;
  }

  .wrapper > div {
    margin: 0.5em;
  }
```

**Comment by PeachScript** [comment]
For this issue #93 , this component only works if it has width, height or both.

In flow layout, this component has `100%` height by default because it is a block element, but in flex layout, this component will be invisible because it has not a `width` property or `flex` property, so you can give this component `width` or `flex` value to fix it through CSS.

But I don't know why you need to take it join the flex layout?

**Comment by Isa79** [comment]
@PeachScript I fixed it with the flex property. But then I replaced the flexbox layout with CSS Grid. And sorry, I don't understand your question.

**Comment by PeachScript** [comment]
@Isa79 it does not matter :P
