### ISSUE TITLE
Suggestion on component API

### ISSUE THREAD

**Issue by asvae** [PeachScript/vue-infinite-loading#13]
I suggest using `@infinite="loadNext"` event watcher instead of passing down parent method. 
Loading state could be handled from parent scope as well:
`:loading="isLoading"`.

Broadcasting and direct parent access are considered dangerous nowadays.

I can provide a pull request if my suggestion rings the bell.

**Comment by PeachScript** [comment]
Thanks for your suggestion!

I readed the changes of Vue2 before release the v2.0.0-rc.1, the Vue2 considered use event bus or Vuex to instead of the event passing.

But I hope users don't need to focus the status(ready/loading/finished/empty) and handle multiple variables when use this component, so I selected use event passing to change the status of this component, and I recommend use the ref directive to get the instance of this component and emit event by it in v2.0.0-rc.1 document, to prevent event Ping-Pong and some dangerous as you say.

If you have a better way to balance "best practice" and easy to use, tell me please, thank you!

**Comment by asvae** [comment]
@PeachScript It's possible to pass down the promise returning closure at least. Will prevent dispatches at least.
``` javascript
// directive
methods: {
    onInfinite (){
         this.isLoading = true
         let next = () => {this.isLoading = false}
         this.loading(next)
    }
}

// parent
<component vm-infinite-loading :loading="load"></component>
methods: {
    load (next){
        ajax().then(next)
    }
}
```

Simple as that.

**Comment by PeachScript** [comment]
It's very interesting! Thank you very much!

How do you think pass the `this.$emit` method into the call back function to instead of the `ref` directive?

```
// parent
methods: {
  load(emitter) {
    ajax().then(() => {
      emitter('$infiniteLoading:complete');
    });
  }
}
```

**Comment by asvae** [comment]
Glad you liked it.

And no, I think `ref` is much cleaner than some `emitter`. Even in terms of lines of code.
