### ISSUE TITLE
Keep $state (.complete or .loaded) globally (or via Vuex)

### ISSUE THREAD

**Issue by MarvinMiles** [PeachScript/vue-infinite-loading#194]
Hello! Thank you for your work!

I am storing my axios results in vuex while scrolling. When I routing to another page and then coming back to page with InfiniteLoading, my data is the same, but InfiniteLoading triggered again and I receiving "no-results" below.

How can I keep state "complate" and don't trigger InfiniteLoading each time when coming back to previous page with InfiniteLoading.

Thank you!

**Comment by PeachScript** [comment]
Glad you like it, how about [`keep-alive`](https://vuejs.org/v2/api/#keep-alive)?

**Comment by MarvinMiles** [comment]
@PeachScript Hi!

In case navigation to previous page "keep-alive" works nicely. Thanks! 

But... I am also using Internationalization plugin "i18n". So when I changing locale and routing between "domain.com/**en**/page" and "domain.com/**ru**/page" my data keeps the same (thx to vuex) but InfiniteLoading restarts.

Any another way to keep state globally?

**Comment by PeachScript** [comment]
If the multiple routes using the same component, all the state will be keep if you change route between them, you can read more about it in the [`beforeRouteUpdate` router guards](https://router.vuejs.org/guide/advanced/navigation-guards.html#in-component-guards), so I don't understand why your `InfiniteLoading` component was restarted, because the route component still exists.

**Comment by wujekbogdan** [comment]
@PeachScript
I have another use case that would require `$state` to be a Vue instance property. My `loadMore` method doesn't do any asynchronous work. It just changes a single property on the Vue instance.  There's a watcher that watches that property and performs some asynchronous works. So I can't access `$state` there because it's available only for the `loadMore` method.

**Comment by oroalej** [comment]
When using Vuex, i'm getting `$attrs is readonly`. Does anybody know how to fix this?
