### ISSUE TITLE
With position:absolute doesn't stop loading

### ISSUE THREAD

**Issue by baloodevil** [PeachScript/vue-infinite-loading#212]
### Version
2.4.3

### Vue.js version
v2.5.21

### Reproduction Link
https://jsfiddle.net/qfb1yL7v/

### Steps to reproduce
Change the example to use position:absolute (and add object properties to have a 'top' value).

### What is Expected?
That the loading of more data doesn't occur until the user scrolls down the the bottom.

### What is actually happening?
Loading all pages occurs immediately.

**Comment by PeachScript** [comment]
This problem was caused by the layout, because this component cannot get list height through it's offset position. So you can add `position: relative` and `top` value for the `InfiniteLoading` component, and make sure it always at the bottom of the list, it will works properly.

*Note: if you want to use `position: absolute` for this component, you must declare a valid width for it.*
