### ISSUE TITLE
[Feature Request] Possibility to configure throttle in component and not only as a plugin.

### ISSUE THREAD

**Issue by lwxbr** [PeachScript/vue-infinite-loading#262]
Hello, I just to configure the throttle option that is already offered in plugin but in component level, thanks!

PS.: I saw that throttling the infinite loading using the plugin the loader doesn't appear, I don't know if it is a bug or it is intended.

**Comment by sebmor** [comment]
Very handy if you use the infinite loader for various elements which have different amounts of data or different utility

**Comment by lwxbr** [comment]
Yeah, the main idea is:

```
<infinite-loading :identifier="infiniteId" @infinite="infiniteHandler" :throttle="3000"></infinite-loading> 
<!-- it will throttle the request or a async operation for 3 seconds -->
```

**Comment by PeachScript** [comment]
When I designing the API, I thought throttle should be a uniform behavior in global, so I put it into the global config, and I'm curious why you need to use different throttle config in the same project, could you describe your detailed situation here?

**Comment by lwxbr** [comment]
@PeachScript, If we think that way, Loader slot should be global too, there's no reason to use two or three loaders in application, you can use just one. The matter is about component independency and flexibility. I guess that situation would be useful for tests, it is just a improvement, not a new feature that will have to modify the entire API to work. I could do a pull request if you want. How hard would to be you implement a prop that throttles the infinite loading in the component?

**Comment by PeachScript** [comment]
@lwxbr thanks for your description!

Emm...not like `throttle`, global loader was created after loader slot be created, exactly because of some developers want to configure global loader, that's a new feature, you know, I cannot downgrade API :D

I think component API should be minimal and helpful, if only because we can implement it rather than some scenes really need it, we will create many useless APIs, so we can consider it when we really be blocked by it.
