### ISSUE TITLE
Issue when using cacheable components (<keep-alive>)

### ISSUE THREAD

**Issue by nlocascio** [PeachScript/vue-infinite-loading#40]
When using vue-infinite-loading in a cacheable component inside of ```<keep-alive>```, the component will sometimes trigger onInfinite indefinitely while the parent component is inactive (cached).

You can recreate the condition using this [jsfiddle](https://jsfiddle.net/nlocascio/5kes8cgf/):
1. Click "Go to Bar" to activate the Bar component.
2. Immediately click "Go to Foo". This will deactivate/cache Bar and replace it with Foo.
3. In dev console, you'll see that onInfinite continues to run.

I ran into this issue usiung Vue-Router and ```<keep-alive>``` to cache components, and found that the infinite loader would keep runing on cached components.

**Comment by PeachScript** [comment]
Thank you @nlocascio , I will find the real reason and fix it.

**Comment by PeachScript** [comment]
Hi @nlocascio , I have been released a new version `v2.0.4` to fix this problem, you can try it in the [JSFiddle](https://jsfiddle.net/5kes8cgf/3/) that base on yours.

But it only works with Vue.js `v2.2.0` and above, because the nested component's `activated` and `deactivated` lifecycle hooks cannot be trigger in low Vue version(details in [here](http://vuejs.org/v2/api/#keep-alive)). If we want to solve this problem in the lower Vue version, we must handle `activated` and `deactivated` lifecycle hooks in the top-level `keep-alive` component like this:

```js
const AliveComponent = {
  ...
  template: '#bar',
  deactivated() {
    this.$refs.yourInfiniteLoading.isLoading = false;
  },
};
```

**Comment by nlocascio** [comment]
@PeachScript - thanks for pushing the update. I had been thinking of approaching this issue through the distance detection logic in ```getCurrentDistance```. I think it would be better, if possible, to rely on some property from within the DOM to check if the InfiniteLoading component is somewhere on the page instead of relying on anything from the Vue component lifecycle. I'm not even sure this is possible as I don't yet have a full grasp on how component caching works in Vue, but I'll try to reason about the issue when I have some more time. Let me know if you have any other thoughts about it.

**Comment by PeachScript** [comment]
It sounds interesting! I will think about this problem according to your thoughts, perhaps can solve the compatibility problem, keep in touch.

**Comment by PeachScript** [comment]
I found the [key point](https://github.com/vuejs/vue/blob/3209f6f517a4fa44c563cd7cc048fa29be1bc930/src/core/instance/lifecycle.js#L290) in the source code of `Vue.js`, so I think we can use the `_inactive` private property to solve this problem, how do you think about it?

**Comment by stephantabor** [comment]
I'm having this issue still with the newest version (in fact worse after upgrading from 2.0.0 rc5)

My case is a little different though. I have a keep alive page with an infinite loader, and other router-views have infinite loaders as well. The loaders emitting events in the other pages are triggering my keep alive component's loader. 

Here is a an example modified from your previous one: 
https://jsfiddle.net/0nuojLdn/

I'm guessing it's because these are global events. Is there a current limitation of not being able to have two of these active at once?

I haven't looked too deeply at the source, but a quick solution might be to have the events keyed or to call `this.$off` in the `deactivated` hook for all of the events.

**Comment by duyhung85** [comment]
Hi,

I am not sure if this is the same problem that I have. I am using vue-inifinite-loading 2.1.1 and  define router lazy loading
[https://router.vuejs.org/en/advanced/lazy-loading.html](url)

The $InfiniteLoading:loaded' event keeps getting called until my browser crash, never stops. I have to switch back to normal router without the lazy loading and everything's working fine.

**Comment by PeachScript** [comment]
@duyhung85 could you reproduce the problem on [JSFiddle](https://jsfiddle.net) or other website like it?

**Comment by PeachScript** [comment]
@stephantabor sorry, I missed your comment, I will reply as soon as possible.

**Comment by PeachScript** [comment]
@stephantabor , the real reason is, this plugin always listen the scroll event, no matter it be `activated` or `deactivated` by `keep-alive` feature, so when we using it with `keep-alive` feature, and go to the route which contains this plugin, then go to another route and scroll down, this plugin will handle the needless scroll event and cause this problem.

I have released `v2.1.3` to fix it, you can test it with this [JSFiddle](https://jsfiddle.net/0nuojLdn/1/) that base on yours.

Thanks for your feedback!

**Comment by duyhung85** [comment]
Hi @PeachScript ,

I updated to v2.1.3 as you suggested and it fixed my issue.

Thanks

**Comment by PeachScript** [comment]
@duyhung85 you are welcome :)
