### ISSUE TITLE
Both directions scrolling

### ISSUE THREAD

**Issue by daverdalas** [PeachScript/vue-infinite-loading#47]
Hey, I want to implement my infinite list according to this guidelines: https://webmasters.googleblog.com/2014/02/infinite-scroll-search-friendly.html Ex: http://scrollsample.appspot.com/items?page=3
Such a list requires the ability to scroll in two directions. I see that there is a `direction` property but it can only be set to one value. It would be great to have the option to scroll up and dwon with the variable determing direction being pushed to `onInfinite` method.

**Comment by PeachScript** [comment]
Hello, the `direction` property can be set to `top` or `bottom`, have you tried it?

**Comment by ndelvalle** [comment]
@PeachScript Is it possible to use it in a bidirectional way? No just `top` or `bottom` but both at the same time.

**Comment by PeachScript** [comment]
@ndelvalle in fact, if we need a bidirectional list, we also need two load animations, so we can use two `InfiniteLoading` component in one list, one of them load `top`, another one load `bottom`, how do you think about it?

**Comment by PeachScript** [comment]
17 days passed but no reply, I will close this issue, you can reopen it if you need in the future.

**Comment by Radiergummi** [comment]
Hey @PeachScript, sorry for reviving this old issue, but could you add a code example for bidirectional lists to the documentation? I'm currently working on an ERP system for a company with around 11,000 products. I intend to display them as tiles with an image, so as you can imagine, that'll have a huge impact on browser performance once you scroll too much.  
Therefore, I'd like to use another `InfiniteLoading` at the top of the list, I'm just not sure how to do the list handling correctly, because there is no reference to the previous offset, unless I'm keeping track of it somewhere...

**Comment by PeachScript** [comment]
@Radiergummi I think so and will add it in the near future, thanks! And for you problem, maybe this comment can help you: https://github.com/PeachScript/vue-infinite-loading/issues/73#issuecomment-328336620
