### ISSUE TITLE
Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by darrensteelesky** [PeachScript/vue-infinite-loading#59]
I'm just using this as a spinner, so when I do

    <div v-if="loading">
      <infinite-loading></infinite-loading>
    </div>

I get 

Uncaught TypeError: Cannot read property 'call' of undefined

**Comment by PeachScript** [comment]
I think we cannot use this component just as a spinner, because it will listen scroll event and try to call the `onInfinite` function, so if you really like these spinners and you want to use them without this component, you can just include the spinner styles like this way:
```js
// in your entry file (suppose you are using Webpack)
require('vue-infinite-loading/src/styles/spinner.less');
```

```html
<!-- in your template -->
<div v-if="loading">
  <!-- or `loading-spiral` `loading-bubbles` `loading-circles` `loading-wave-dots` -->
  <span class="loading-default"></span>
</div>
```

Perhaps you need to add some custom styles to control size and position for the spinners, in fact, you also can use other professional spinner libraries.

**Comment by darrensteelesky** [comment]
Thanks for the quick feedback.  I just went with a font-awesome spinner for now.
