### ISSUE TITLE
"npm run build" occur UglifyJS error

### ISSUE THREAD

**Issue by jun9358** [PeachScript/vue-infinite-loading#60]
i just clone this repo and run build script but i got a error... how can i build?

```
root@aa88a30e9855:/node_modules/vue-infinite-loading# npm run build

> vue-infinite-loading@2.1.3 build /node_modules/vue-infinite-loading
> NODE_ENV=production webpack --progress --hide-modules

Hash: 5b3228007782963eb3d7  
Version: webpack 1.15.0
Time: 196ms
                  Asset     Size  Chunks             Chunk Names
vue-infinite-loading.js  2.09 kB       0  [emitted]  vue-infinite-loading

ERROR in vue-infinite-loading.js from UglifyJs
SyntaxError: Unexpected token: name (InfiniteLoading) [./src/index.js:1,0]
```

**Comment by jun9358** [comment]
um... solved

remove all and retry...

**Comment by Hopingocean** [comment]
'npm run build'
then the result is:
set NODE_ENV=production webpack --config scripts/webpack.config.js -p --progress --hide-modules

and nothing happend, so what should i do? i want to change the bubbles.less @c-basic

**Comment by PeachScript** [comment]
Sorry @Hopingocean , build script only use to develop, so the compatibility has not been considered. It is not recommended because change spinner color is too complex, maybe I will provide a color property for it in the future, for now, you can use other configurable 3rd-party spinners via the `spinner` slot.
