### ISSUE TITLE
Styling for "no-more" and "no-results" messages

### ISSUE THREAD

**Issue by syn-zeta** [PeachScript/vue-infinite-loading#80]
https://github.com/PeachScript/vue-infinite-loading/blob/8090c1ac4a8abcf0b39dd43b67d77b9ac310eb48/src/components/InfiniteLoading.vue#L170-L171

The component should allow the `color` and `font-size` of these messages to be inherited from the using application. Currently, this has to be overridden with an internal class rule with `!important`, which is not very clean.

**Comment by PeachScript** [comment]
@syn-zeta except override with `!important`, another little complex way can did it:
```html
<span slot="no-results">
  <span class="your-customize-class">This is a message.</span>
</span>
```

Do you have any idea about the way to inherit from the using application?

**Comment by syn-zeta** [comment]
Oh, to let it inherit would mean that it is not specified in the component, and the span would get the styling from one of its ancestor. For instance, this issue section on GitHub gets the font styling from the body:

![image](https://user-images.githubusercontent.com/26761352/30505716-51c8beaa-9a2b-11e7-802c-cabd06a8d394.png)

**Comment by PeachScript** [comment]
Hi @syn-zeta , I added a new rule about the default styles in the new version `v2.4.0`, you can check out in the [new docs](https://peachscript.github.io/vue-infinite-loading/guide/configure-load-msg.html#about-hide-default-styles), hope the new rule can help you.

Please comment here if you find any problem :)

**Comment by Szymon-dziewonski** [comment]
@PeachScript I have a problem with messages, was wondering if we can have some flag to either remove styling or not display/hide those messages/slots. In my case I don't want to display `no-more` and yet I cant do it other than setting 

```
Vue.use(InfiniteLoading, {
  slots: {
    noMore: '',
  },
});
```
and 
```
<!-- eslint-disable-next-line vue/no-parsing-error -->
<template #no-more v-text=" " />
```
prop on component like `hide-no-more` or `hide-no-results` would be sufficient for just hiding.
And as for styling IMHO would be better to not at styling at all, users can do them by themselves I bet 99% don't need those styles :(

Cant use proposed tagged slot since its deprecated in vue.js 2.6 https://vuejs.org/v2/guide/components-slots.html#Deprecated-Syntax

**Comment by hardik-baraiya-123456** [comment]
```
<InfiniteLoading @infinite="load">
          <template #complete><div></div></template>
        </InfiniteLoading>
```

**Comment by sanjayHN3392** [comment]
> ```
> <InfiniteLoading @infinite="load">
>           <template #complete><div></div></template>
>         </InfiniteLoading>
> ```

Thanks it works for me
